project_id = "koqckietdzghuxresjsv"

[functions.lookup-user-by-email]
verify_jwt = false

[functions.invite-user]
verify_jwt = false

[functions.create-workspace-from-lead]
verify_jwt = false

[functions.analyze-constraint]
verify_jwt = false
